---
platform: linux

image_resource:
  type: docker-image
  source:
    # Any image with git installed will do but we already use this one
    # thus it will be cached
    repository: alpine/git
    tag: "1.0.4"

inputs:
  - name: final-version
  - name: next-version
  - name: source 

outputs:
  - name: updated-source

params:
  RELEASE_BRANCH: ""
  FINAL_VERSION_SUFFIX: ""
  NEXT_VERSION_SUFFIX: ""

run:
  path: /bin/sh
  args:
    - source/ci/tasks/bump-pom-version.sh